"""add mod stats

Revision ID: 4441d002c874
Revises: b9787b2767e1
Create Date: 2026-07-12 12:11:48.687490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4441d002c874'
down_revision: Union[str, Sequence[str], None] = 'b9787b2767e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'mods', sa.Column('endorsements', sa.BigInteger(), nullable=False, server_default='0')
    )
    op.add_column(
        'mods', sa.Column('downloads', sa.BigInteger(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mods', 'downloads')
    op.drop_column('mods', 'endorsements')
    # ### end Alembic commands ###
