"""init mods, guilds, subscriptions

Revision ID: 92b009b2403a
Revises: 
Create Date: 2026-07-08 14:03:50.122190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b009b2403a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('mods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_domain', sa.String(length=100), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('picture_url', sa.String(length=500), nullable=False),
    sa.Column('nexus_updated_at', sa.BigInteger(), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_domain', 'mod_id', name='uq_game_mod')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('mod_pk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mod_pk'], ['mods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'mod_pk', name='uq_guild_mod')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('mods')
    op.drop_table('guilds')
    # ### end Alembic commands ###
