"""add mod summary

Revision ID: b9787b2767e1
Revises: 92b009b2403a
Create Date: 2026-07-12 00:38:39.538260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9787b2767e1'
down_revision: Union[str, Sequence[str], None] = '92b009b2403a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'mods', sa.Column('summary', sa.String(length=500), nullable=False, server_default='')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mods', 'summary')
    # ### end Alembic commands ###
